module.exports = {
  NULL_VALUE: "필요한 값이 없습니다.",
  OUT_OF_VALUE: "파라미터 값이 잘못 되었습니다.",

  /* 회원가입 */
  SIGN_UP_SUCCESS: "회원 가입 성공.",
  SIGN_UP_FAIL: "회원 가입 실패.",
  SIGN_IN_SUCCESS: "로그인 성공.",
  SIGN_IN_FAIL: "로그인 실패.",
  USER_LOGOUT: "사용자 로그아웃",
  ALREADY_ID: "존재하는 ID 입니다.",
  CHECK_ID_SUCCESS: "ID 중복검사 성공",
  CHECK_ID_FAIL: "ID 중복검사 실패",
  ALREADY_PHONE: "존재하는 핸드폰 번호 입니다.",
  NO_USER: "존재하지않는 유저 id 입니다.",
  ALREADY_EMAIL: "이미 존재하는 이메일 입니다.",
  CHECK_EMAIL_SUCCESS: "Email 중복검사 성공",
  CHECK_EMAIL_FAIL: "Email 중복검사 실패",
  NO_EMAIL: '존재하지 않는 이메일 입니다.',
  RULE_MISS_MATCH_ID: "아이디 생성 규칙이 불일치합니다",
  RULE_MISS_MATCH_PW: "비밀번호 생성 규칙이 불일치합니다",
  RULE_MISS_MATCH_EMAIL: "이메일 생성 규칙이 불일치합니다",
  MISS_MATCH_PW: "비밀번호가 일치하지 않습니다",

  /* User */
  READ_USER_SUCCESS: "사용자 조회 성공",
  READ_USER_ALL_SUCCESS: "전체 사용자 조회 실패",
  READ_USER_FAIL: "사용자 조회 성공",
  READ_USER_ALL_FAIL: "전체 사용자 조회 실패",
  UPDATE_USER_SUCCESS: "사용자 업데이트 성공",
  UPDATE_USER_FAIL: "사용자 업데이트 실패",
  DELETE_USER_SUCCESS: "사용자 삭제 성공",
  DELETE_USER_FAIL: "사용자 삭제 실패",
  FIND_EMAIL_SUCCESS: "사용자 이메일 찾기 성공",
  FIND_EMAIL_FAIL: "사용자 이메일 찾기 실패",
  RESET_PASSWORD_SUCCESS: "사용자 비밀번호 초기화 성공",
  RESET_PASSWORD_FAIL: "사용자 비밀번호 초기화 실패",
  EMAIL_CHECK_SUCCESS: "이메일 중복체크 성공",
  EMAIL_CHECK_FAIL: "이메일 중복체크 싱패",
  DELETE_ACCOUNT_SUCCESS: "계정 삭제 성공",
  DELETE_ACCOUNT_FAIL: "계정 삭제 실패",
  SET_MARKETING_SUCCESS: "마케팅 수신 설정 성공",
  SET_MARKETING_FAIL: "마케팅 수신 설정 실패",
  PW_CHECK_SUCCESS: "비밀번호 일치",
  PW_CHECK_FAIL: "비밀번호 체크 실패",
  CHANGE_PW_SUCCESS: "비밀번호 변경 성공",
  CHANGE_PW_FAIL: "비밀번호 변경 실패",
  GET_USER_SET_SUCCESS: "유저 계정 설정 조회 성공",
  GET_USER_SET_FAIL: "유저 계정 설정 조회 실패",
  NO_EMAIL: '존재하지 않는 이메일',
  UNAUTHORIZED: '인증 오류',

  /* 프로필 */
  READ_PROFILE_SUCCESS: "프로필 조회 성공",
  READ_PROFILE_FAIL: "프로필 조회 실패",

  /* 상품 */
  NEED_COUNT: "상품의 수량 필요",
  REGISTER_PRODUCT_SUCCESS: "상품 등록 성공",
  REGISTER_PRODUCT_FAIL: "상품 등록 실패",
  FIND_PRODUCT_BY_ID_SUCCESS: "특정 상품 조회 성공",
  FIND_PRODUCT_BY_ID_FAIL: "특정 상품 조회 실패",
  NO_EXIST_PRODUCT: "존재하지 않는 상품",
  FIND_ALL_PRODUCTS_SUCCESS: "전체 상품 조회 성공",
  FIND_ALL_PRODUCTS_FAIL: "전체 상품 조회 실패",
  FIND_RECENT_PRODUCTS_SUCCESS: "최신 상품 조회 성공",
  FIND_RECENT_PRODUCTS_FAIL: "최신 상품 조회 실패",
  FIND_ALL_PRODUCTS_BY_ONE_CATEGORY_SUCCESS: "1개 카테고리로 상품 조회 성공",
  FIND_ALL_PRODUCTS_BY_ONE_CATEGORY_FAIL: "1개 카테고리로 상품 조회 실패",
  FIND_ALL_AEROBIC_SUCCESS: "유산소 상품 조회 성공",
  FIND_ALL_AEROBIC_FAIL: "유산소 상품 조회 실패",
  FIND_ALL_WEIGHT_SUCCESS: "웨이트 상품 조회 성공",
  FIND_ALL_WEIGHT_FAIL: "웨이트 상품 조회 실패",
  FIND_ALL_AIDS_SUCCESS: "운동보조기구 상품 조회 성공",
  FIND_ALL_AIDS_FAIL: "운동보조기구 상품 조회 실패",
  FIND_ALL_MASSAGE_SUCCESS: "마사지 상품 조회 성공",
  FIND_ALL_MASSAGE_FAIL: "마사지 상품 조회 실패",
  FIND_ALL_ASSISTANT_SUCCESS: "보조 상품 조회 성공",
  FIND_ALL_ASSISTANT_FAIL: "보조 상품 조회 실패",
  SEARCH_PRODUCT_SUCCESS: "상품 검색 성공",
  SEARCH_PRODUCT_FAIL: "상품 검색 실패",
  SEARCH_DETAIL_PRODUCT_SUCCESS: "상품 상세 검색 성공",
  SEARCH_DETAIL_PRODUCT_FAIL: "상품 상세 검색 실패",
  UPDATE_PRODUCT_SUCCESS: "상품 수정 성공",
  UPDATE_PRODUCT_FAIL: "상품 수정 실패",
  DELETE_PRODUCT_SUCCESS: "상품 삭제 성공",
  DELETE_PRODUCT_FAIL: "상품 삭제 실패",

  /* 배너 */
  REGISTER_BANNER_SUCCESS: "배너 등록 성공",
  REGISTER_BANNER_FAIL: "배너 등록 실패",
  FIND_BANNER_BY_ID_SUCCESS: "특정 배너 조회 성공",
  FIND_BANNER_BY_ID_FAIL: "특정 상품 조회 실패",
  NO_EXIST_BANNER: "존재하지 않는 배너",
  FIND_ALL_BANNER_SUCCESS: "전체 상품 조회 성공",
  FIND_ALL_BANNER_FAIL: "전체 상품 조회 실패",
  FIND_AVAILABLE_BANNER_SUCCESS: "유효한 배너 조회 성공",
  FIND_AVAILABLE_BANNER_FAIL: "유효한 배너 조회 실패",
  UPDATE_BANNER_SUCCESS: "배너 수정 완료",
  UPDATE_BANNER_FAIL: "배너 수정 실패",
  SEARCH_BANNER_BY_STARRTDATE_SUCCESS: "시작 날짜로 배너 검색 성공",
  SEARCH_BANNER_BY_STARRTDATE_FAIL: "시작 날짜로 배너 검색 실패",
  SORT_BANNER_SUCCESS: "배너 정렬 성공",
  SORT_BANNER_FAIL: "배너 정렬 실패",

  /* 주문 내역 */

  FIND_ALL_ORDERHISTORY_SUCCESS: "전체 주문 내역 성공",
  FIND_ALL_ORDERHISTORY_FAIL: "전체 주문 내역 실패",
  REGISTER_ORDER_SUCCESS: "주문 등록 성공",
  REGISTER_ORDER_FAIL: "주문 등록 실패",
  FIND_MY_ORDER_SUCCESS: "나의 주문 내역 조회 성공",
  FIND_MY_ORDER_FAIL: "나의 주문 내역 조회 실패",
  SEARCH_ORDER_BY_ID_SUCCESS: "ID로 주문 내역 검색 성공",
  SEARCH_ORDER_BY_ID_FAIL: "ID로 주문 내역 검색 실패",
  NO_EXIST_ORDER: "존재 하지 않는 주문 내역",
  SEARCH_MY_ORDER_SUCCESS: "나의 주문 내역 기간으로 검색 성공",
  SEARCH_MY_ORDER_FAIL: "나의 주문 내역 기간으로 검색 실패",
  SEARCH_ALL_ORDER_SUCCESS: "모든 주문 내역 기간으로 검색 성공",
  SEARCH_ALL_ORDER_FAIL: "모든 주문 내역 기간으로 검색 실패",
  UPDATAE_STATUS_SUCCESS: "STATUS 수정 완료",
  UPDATE_STATUS_FAIL: "STATUS 수정 실패",
  INVALID_DATE_INPUT: "입력 날짜 이상",
  INVALID_STAUTS: "현재 STATUS 4 이상",


  /* 장바구니 */
  GET_BASKET_SUCCESS: "장바구니 조회 성공",
  GET_BASKET_FAIL: "장바구니 조회 실패",
  PUT_IN_BASKET_SUCCESS: "장바구니 추가 성공",
  PUT_IN_BASKET_FAIL: "장바구니 추가 실패",
  LACK_PRODUCT: "상품의 수량 부족",
  DELETED_PRODUCT: "삭제된 상품",
  SO_SMALL_COUNT: "너무 낮은 Count",
  UPDATE_BASKET_SUCCESS: "장바구니 항목 수정 완료",
  UPDATE_BASKET_FAIL: "장바구니 항목 수정 실패",
  DELETE_BASKET_SUCCESS: "장바구니 항목 삭제 완료",
  DELETE_BASKET_FAIL: "장바구니 항목 삭제 실패",
  NO_EXIST_ELEMENT: "존재하지 않는 항목",

  /* 배송지 */
  ADD_DESTINATION_SUCCESS: "배송지 추가 성공",
  ADD_DESTINATION_FAIL: "배송지 추가 실패",
  EXIST_DESTINATION: "존재하는 배송지",
  NO_EXIST_DESTINATION: "존재하지 않는 배송지",
  UPDATE_DESTINATION_SUCCESS: "배송지 수정 성공",
  UPDATE_DESTINATION_FAIL: "배송지 수정 실패",
  FIND_DESTINATION_BY_ID_SUCCESS: "특정 배송지 조회 성공",
  FIND_DESTINATION_BY_ID_FAIL: "특정 배송지 조회 실패",
  FIND_ALL_MY_DESTINATION_SUCCESS: "배송지 조회 성공",
  FIND_ALL_MY_DESTINATION_FAIL: "배송지 조회 실패",
  DELETE_DESTINATION_SUCCESS: "배송지 삭제 성공",
  DELETE_DESTINATION_SUCCESS: "배송지 삭제 성공",


  /* 쿠폰 */
  REGISTER_COUPON_SUCCESS: "쿠폰 등록 성공",
  REGISTER_COUPON_FAIL: "쿠폰 등록 실패",
  EXIST_COUPON: "이미 존재하는 쿠폰 코드",
  SO_BIG_DISCOUNT_RATE: "너무 큰 할인율",
  FIND_ALL_COUPON_SUCCESS: "모든 쿠폰 조회 성공",
  FIND_ALL_COUPON_FAIL: "모든 쿠폰 조회 성공",
  ISSUE_COUPON_ALL_SUCCESS: "모두에게 쿠폰 발급 성공",
  ISSUE_COUPON_ALL_FAIL: "모두에게 쿠폰 발급 실패",
  ISSUE_COUPON_USER_SUCCESS: "유저에게 쿠폰 발급 성공",
  ISSUE_COUPON_USER_FAIL: "유저에게 쿠폰 발급 실패",
  ALREADY_COUPON: "이미 소지하고있는 쿠폰",
  SEARCH_ALL_COUPON_BY_COUPON_SUCCESS: "쿠폰 소지 유저 조회 성공",
  SEARCH_ALL_COUPON_BY_COUPON_FAIL: "쿠폰 소지 유저 조회 실패",
  SEARCH_ALL_COUPON_BY_USER_SUCCESS: "유저가 소지한 쿠폰 조회 성공",
  SEARCH_ALL_COUPON_BY_USER_FAIL: "유저가 소지한 쿠폰 조회 실패",
  NO_AVAILABLE_USER_COUPON: "해당 쿠폰 소지하지 않음",
  NO_AVAILABLE_COUPON: "사용 불가능한 쿠폰 코드",
  AVAILABLE_COUPON: "사용 가능한 쿠폰 코드",
  NO_EXIST_COUPON: "소지한 쿠폰 없음",
  NO_EXIST_USER: "소지한 유저 없음",
  DELETED_COUPON_SUCCESS: "쿠폰 삭제 성공",
  DELETED_COUPON_FAIL: "쿠폰 삭제 성공",

  /* 상품평 */
  REGISTER_REVIEW_SUCCESS: "상품평 등록 성공",
  REGISTER_REVIEW_FAIL: "상품평 등록 실패",
  REIVEW_TOO_LONG: "후기 길이 초과",
  GET_REVIEW_SUCCESS: "상품평 조회 성공",
  GET_REVIEW_FAIL: "상품평 조회 실패",

  /* 문의 */
  REGISTER_QUESTION_SUCCESS: "문의 등록 성공",
  REGISTER_QUESTION_FAIL: "문의 등록 실패",
  REGISTER_ANSWER_SUCCESS: "답변 등록 성공",
  REGISTER_ANSWER_FAIL: "답변 등록 실패",
  GET_QUESTION_DETAIL_SUCCESS: "문의 상세조회 성공",
  GET_QUESTION_DETAIL_FAIL: "문의 상세조회 실패",
  GET_ALL_QUESTION_SUCCESS: "전체 문의 조회 성공",
  GET_ALL_QUESTION_FAIL: "전체 문의 조회 실패",
  GET_ORDER_QUESTION_SUCCESS: "주문내역 문의 조회 성공",
  GET_ORDER_QUESTION_FAIL: "주문내역 문의 조회 실패",
  TITLE_TOO_LONG: "문의 제목 길이 초과",

  /* 판매 정보 */
  GET_ALL_TOTAL_COST_SUCCESS: "모든 판매 누적 금액 조회 성공",
  GET_ALL_TOTAL_COST_FAIL: "모든 판매 누적 금액 조회 실패",
  GET_DATE_TOTAL_COST_SUCCESS: "날짜 필터링 판매 누적 금액 조회 성공",
  GET_DATE_TOTAL_COST_FAIL: "날짜 필터링 판매 누적 금액 조회 실패",
  GET_TOP_PRODUCTS_SUCCESS: "상위 상품 조회 성공",
  GET_TOP_PRODUCTS_FAIL: "상위 상품 조회 실패",
  GET_TOP_CATEGORY_SUCCESS: "상위 5개 카테고리 조회 성공",
  GET_TOP_CATEGORY_FAIL: "상위 5개 카테고리 조회 실패",

  /* 카테고리 */
  NO_CATEGORY: "존재하지 않는 카테고리",

  /* 서버에러 */
  INTERNAL_SERVER_ERROR: "서버 내부 오류",
}
